main.exe: main.c timers.c messages.c
	gcc -g main.c timers.c messages.c -o main.exe
#is it possible to automatically run program 

#command_1:
#    echo "test"

#main.exe: main.c
#	gcc main.c -o main.exe